### PR TITLE
Localization Fixes

### PR DESCRIPTION
**Pull request by am385**
Add priconfig template
Update readme
Update Package Version #

Remove extra localize.js file

### CODE REVIEW

**Comment by am385** [comment]
Found some more fixes that need to get pushed through. I already updated the package version number too.

If this pull looks ok can you guys go ahead and publish this package.

**Comment by f2bo** [comment]
@am385 @boyofgreen Everything seems to be in order though I can only handle a **quick** test at the moment.

I did find a slight problem in the **Readme** file. One of the code block delimiters is missing so the rendering of code and text blocks is inverted throughout the document. I can fix that if you're fine with me updating it. 

Also, I noticed that the text indicates using both the -p and -f parameters.

```
manifoldjs -m "<PATH-TO-EXTENSION-DIRECTORY>\manifest.json" -p edgeextension -f edgeextension [-l debug]
```

I believe we are forcing the manifest format when the edgeextension platform is specified, so using the -f parameter shouldn't be necessary. @estebanlopez: Can you confirm?

**Comment by estebanlopez** [comment]
It's not that the format is forced, but it will be automatically detected if the manifest is valid (i.e.: all members are [valid properties](https://github.com/manifoldjs/manifoldjs-lib/blob/master/lib/manifestTools/transformations/edgeextension.js#L19)).

The -f parameter should be used if the manifest contains additional, unknown members that make the format validation fail.

**Comment by am385** [comment]
@f2bo @estebanlopez @boyofgreen 

That would be awesome if you could fix the code delimiter. I am officially on Paternity Leave and don't have time to at the moment. 

We are using both the -f and the -p to ensure that edgeextension are the only platform running and that the formatting passes without testing as extensions can be malformed and still work. For example a chrome format could work on Edge as long as it still has at least the required properties. We ignore the rest of the properties.

**Comment by boyofgreen** [comment]
Hi Andrew, we sure will help out.  Thanks for seeing this through while out on leave.  I'm traveling today, but I'll do a merge once  @f2bo ads the fix.  Fernando, will this be a second PR or a replacement of this one?  I can push out then up manifoldjs to 0.6.1 so users get the changes.

**Comment by f2bo** [comment]
@boyofgreen  I've already applied the fix. It's been added to this PR.

**Comment by boyofgreen** [comment]
Oh, I didn't know you could do that.   @am385 are okay with me pushing this out without going to xanifold first?  I can do this today.

**Pull request merged**
