### PR TITLE
Remove 'sr' from the accepted language codes

### PR DESCRIPTION
**Pull request by am385**

### CODE REVIEW

**Comment by am385** [comment]
@boyofgreen @mconverti @f2bo

Can someone take a quick look at this. We had a request to remove 'sr' as a valid language code

**Comment by boyofgreen** [comment]
sure, we are going to do a 0.7.5 release real soon for the windows platform, we can work this into it as well. @msrodri can you look at this on Monday and add into the 0.7.5 release?

**Comment by ghost** [comment]
@boyofgreen sure, we'll include this change into the roadmap for the upcoming releases. Could you grant me access to merge the PR? Seems that I don't have the right permissions.

**Comment by boyofgreen** [comment]
done

**Pull request merged**
